// Two lists or two maps whose members hold the null value or are absent,
// against the reference's answers at v9.4.2.
//
// The reference compares the members of two containers by term: two members
// holding the null value are the same member, and so are two absent members,
// although the null value and the absence at the top level keep their own rule
// (a loose comparison of two of either answers the absence). Each row is a
// source, the context it runs against, and the answer the reference gave for
// it. The same rows are in the reference transcript, under `member-equality/`,
// with the reference's answers as it recorded them; this table holds them
// beside the source so a failing row reads as the comparison it is.
//
// The rows go beyond the members that moved: an equal and an unequal pair
// beside each, the strict family beside the loose one, membership both ways,
// the top-level null value and absence that do not move, and date, datetime and
// duration members that compare equal on both sides. Two orderings are here
// because an ordering of two lists walks their leading members with member
// equality, so a leading list or map that holds the null value now steps past
// rather than stopping the ordering.
//
// Sabotage: restoring the reads that turned a stored null member into the
// absence (`?? Undefined` on each member read in `valuesEqual` and
// `strictlyEqual`, in src/evaluator.ts) turns this table red on the member
// rows, and so does comparing two absent members with `valuesEqual` itself
// rather than by identity in `membersEqual`. Each was run and reverted.

import { describe, expect, it } from "vitest";
import { evaluate } from "../src/index.js";

type Row = readonly [source: string, context: Record<string, unknown>, answer: boolean | undefined];

const ROWS: readonly Row[] = [
  ["{line2: null} == {line2: null}", {}, true],
  ["{line2: null} != {line2: null}", {}, false],
  ["{line2: null} === {line2: null}", {}, true],
  ["{line2: null} !== {line2: null}", {}, false],
  ["{line2: null} == {}", {}, false],
  ["{line2: null} != {}", {}, true],
  ["{line2: null} === {}", {}, false],
  ["{line2: null} !== {}", {}, true],
  ["{} == {}", {}, true],
  ["{} != {}", {}, false],
  ["{} === {}", {}, true],
  ["{} !== {}", {}, false],
  ["{plan: 1} == {plan: 1}", {}, true],
  ["{plan: 1} != {plan: 1}", {}, false],
  ["{plan: 1} === {plan: 1}", {}, true],
  ["{plan: 1} !== {plan: 1}", {}, false],
  ["{plan: 1} == {plan: 1.0}", {}, true],
  ["{plan: 1} != {plan: 1.0}", {}, false],
  ["{plan: 1} === {plan: 1.0}", {}, false],
  ["{plan: 1} !== {plan: 1.0}", {}, true],
  ["{plan: 1, tier: 2} == {tier: 2, plan: 1}", {}, true],
  ["{plan: 1, tier: 2} != {tier: 2, plan: 1}", {}, false],
  ["{plan: 1, tier: 2} === {tier: 2, plan: 1}", {}, true],
  ["{plan: 1, tier: 2} !== {tier: 2, plan: 1}", {}, false],
  ["{plan: {tier: null}} == {plan: {tier: null}}", {}, true],
  ["{plan: {tier: null}} != {plan: {tier: null}}", {}, false],
  ["{plan: {tier: null}} === {plan: {tier: null}}", {}, true],
  ["{plan: {tier: null}} !== {plan: {tier: null}}", {}, false],
  ["{line2: null} == {line3: null}", {}, false],
  ["{line2: null} != {line3: null}", {}, true],
  ["{line2: null} === {line3: null}", {}, false],
  ["{line2: null} !== {line3: null}", {}, true],
  ["{line2: null, line3: 1} == {line2: null, line3: 1}", {}, true],
  ["{line2: null, line3: 1} != {line2: null, line3: 1}", {}, false],
  ["{line2: null, line3: 1} === {line2: null, line3: 1}", {}, true],
  ["{line2: null, line3: 1} !== {line2: null, line3: 1}", {}, false],
  ["{line2: null} == {line2: 1}", {}, false],
  ["{line2: null} != {line2: 1}", {}, true],
  ["{line2: null} === {line2: 1}", {}, false],
  ["{line2: null} !== {line2: 1}", {}, true],
  ["[null] == [null]", {}, true],
  ["[null] != [null]", {}, false],
  ["[null] === [null]", {}, true],
  ["[null] !== [null]", {}, false],
  ["[] == []", {}, true],
  ["[] != []", {}, false],
  ["[] === []", {}, true],
  ["[] !== []", {}, false],
  ["[1, null] == [1, null]", {}, true],
  ["[1, null] != [1, null]", {}, false],
  ["[1, null] === [1, null]", {}, true],
  ["[1, null] !== [1, null]", {}, false],
  ["[[null]] == [[null]]", {}, true],
  ["[[null]] != [[null]]", {}, false],
  ["[[null]] === [[null]]", {}, true],
  ["[[null]] !== [[null]]", {}, false],
  ["[1] == [1.0]", {}, true],
  ["[1] != [1.0]", {}, false],
  ["[1] === [1.0]", {}, false],
  ["[1] !== [1.0]", {}, true],
  ["[{line2: null}] == [{line2: null}]", {}, true],
  ["[{line2: null}] != [{line2: null}]", {}, false],
  ["[{line2: null}] === [{line2: null}]", {}, true],
  ["[{line2: null}] !== [{line2: null}]", {}, false],
  ["[null] == [1]", {}, false],
  ["[null] != [1]", {}, true],
  ["[null] === [1]", {}, false],
  ["[null] !== [1]", {}, true],
  ["[null, 1] == [null, 2]", {}, false],
  ["[null, 1] != [null, 2]", {}, true],
  ["[null, 1] === [null, 2]", {}, false],
  ["[null, 1] !== [null, 2]", {}, true],
  ["billing == shipping", { billing: { line2: null }, shipping: { line2: null } }, true],
  ["billing != shipping", { billing: { line2: null }, shipping: { line2: null } }, false],
  ["billing === shipping", { billing: { line2: null }, shipping: { line2: null } }, true],
  ["billing == billing", { billing: { line2: null }, shipping: { line2: null } }, true],
  ["billing != billing", { billing: { line2: null }, shipping: { line2: null } }, false],
  ["billing == billing", { billing: { plan: 1 } }, true],
  ["holds == middle_name", { holds: null, middle_name: null }, undefined],
  ["holds != middle_name", { holds: null, middle_name: null }, undefined],
  ["holds === middle_name", { holds: null, middle_name: null }, true],
  ["holds !== middle_name", { holds: null, middle_name: null }, false],
  [
    "billing.referrer == shipping.referrer",
    { billing: { line2: null }, shipping: { line2: null } },
    undefined,
  ],
  [
    "billing.referrer != shipping.referrer",
    { billing: { line2: null }, shipping: { line2: null } },
    undefined,
  ],
  [
    "billing.referrer === shipping.referrer",
    { billing: { line2: null }, shipping: { line2: null } },
    true,
  ],
  [
    "billing.referrer !== shipping.referrer",
    { billing: { line2: null }, shipping: { line2: null } },
    false,
  ],
  ["billing.referrer == shipping.referrer", { billing: {}, shipping: {} }, undefined],
  ["billing.referrer != shipping.referrer", { billing: {}, shipping: {} }, undefined],
  ["billing.referrer === shipping.referrer", { billing: {}, shipping: {} }, true],
  ["billing.referrer !== shipping.referrer", { billing: {}, shipping: {} }, false],
  [
    "billing.line2 == shipping.line2",
    { billing: { line2: null }, shipping: { line2: null } },
    undefined,
  ],
  ["visited == steps", { steps: [null, 1], visited: [null, 1] }, true],
  ["visited == steps", { steps: [{ line2: null }], visited: [{ line2: null }] }, true],
  ["{plan: 1} == [1]", {}, undefined],
  ["{plan: 1} != [1]", {}, undefined],
  ["{} == []", {}, undefined],
  ["{} != []", {}, undefined],
  ["{} === []", {}, false],
  ["{plan: 1} == null", {}, undefined],
  ["{plan: 1} != null", {}, undefined],
  ["{line2: null} == null", {}, undefined],
  ["[1] == null", {}, undefined],
  ["[1] != null", {}, undefined],
  ["[null] == null", {}, undefined],
  ["[] == null", {}, undefined],
  ["null == null", {}, undefined],
  ["null != null", {}, undefined],
  ["[[null], 1] < [[null], 2]", {}, true],
  ["[{line2: null}, 1] < [{line2: null}, 2]", {}, true],
  ["null in [null]", {}, true],
  ["{line2: null} in [{line2: null}]", {}, true],
  ["[null] in [[null]]", {}, true],
  ["{plan: 1} in [{plan: 1}]", {}, true],
  ["[1] in [[1.0]]", {}, true],
  ["[{line2: null}] contains {line2: null}", {}, true],
  ["[[null]] contains [null]", {}, true],
  ["[null] contains null", {}, true],
  ["[{plan: 1}] contains {plan: 1}", {}, true],
  ["{line2: null} in [{}]", {}, false],
  ["1 in [1.0]", {}, true],
  ["billing in [shipping]", { billing: { line2: null }, shipping: { line2: null } }, true],
  ["[billing] contains shipping", { billing: { line2: null }, shipping: { line2: null } }, true],
  ["billing !== shipping", { billing: { line2: null }, shipping: { line2: null } }, false],
  [
    "billing == shipping",
    { billing: { plan: { tier: null } }, shipping: { plan: { tier: null } } },
    true,
  ],
  [
    "billing != shipping",
    { billing: { plan: { tier: null } }, shipping: { plan: { tier: null } } },
    false,
  ],
  [
    "billing === shipping",
    { billing: { plan: { tier: null } }, shipping: { plan: { tier: null } } },
    true,
  ],
  [
    "billing !== shipping",
    { billing: { plan: { tier: null } }, shipping: { plan: { tier: null } } },
    false,
  ],
  ["billing == shipping", { billing: [null], shipping: [null] }, true],
  ["billing != shipping", { billing: [null], shipping: [null] }, false],
  ["billing === shipping", { billing: [null], shipping: [null] }, true],
  ["billing !== shipping", { billing: [null], shipping: [null] }, false],
  [
    "billing == shipping",
    { billing: [[null], { line2: null }], shipping: [[null], { line2: null }] },
    true,
  ],
  [
    "billing != shipping",
    { billing: [[null], { line2: null }], shipping: [[null], { line2: null }] },
    false,
  ],
  [
    "billing === shipping",
    { billing: [[null], { line2: null }], shipping: [[null], { line2: null }] },
    true,
  ],
  [
    "billing !== shipping",
    { billing: [[null], { line2: null }], shipping: [[null], { line2: null }] },
    false,
  ],
  ["billing == shipping", { billing: { line2: null }, shipping: {} }, false],
  ["billing != shipping", { billing: { line2: null }, shipping: {} }, true],
  ["billing === shipping", { billing: { line2: null }, shipping: {} }, false],
  ["billing !== shipping", { billing: { line2: null }, shipping: {} }, true],
  ["{line2: undefined} == {line2: undefined}", {}, true],
  ["{line2: undefined} != {line2: undefined}", {}, false],
  ["{line2: undefined} === {line2: undefined}", {}, true],
  ["{line2: undefined} !== {line2: undefined}", {}, false],
  ["{line2: referrer} == {line2: referrer}", {}, true],
  ["{line2: referrer} != {line2: referrer}", {}, false],
  ["{line2: referrer} === {line2: referrer}", {}, true],
  ["{line2: referrer} !== {line2: referrer}", {}, false],
  ["{plan: {tier: undefined}} == {plan: {tier: undefined}}", {}, true],
  ["{plan: {tier: undefined}} != {plan: {tier: undefined}}", {}, false],
  ["{plan: {tier: undefined}} === {plan: {tier: undefined}}", {}, true],
  ["{plan: {tier: undefined}} !== {plan: {tier: undefined}}", {}, false],
  ["{plan: {tier: referrer}} == {plan: {tier: referrer}}", {}, true],
  ["{plan: {tier: referrer}} != {plan: {tier: referrer}}", {}, false],
  ["{plan: {tier: referrer}} === {plan: {tier: referrer}}", {}, true],
  ["{plan: {tier: referrer}} !== {plan: {tier: referrer}}", {}, false],
  ["[undefined] == [undefined]", {}, true],
  ["[undefined] != [undefined]", {}, false],
  ["[undefined] === [undefined]", {}, true],
  ["[undefined] !== [undefined]", {}, false],
  ["[referrer] == [referrer]", {}, true],
  ["[referrer] != [referrer]", {}, false],
  ["[referrer] === [referrer]", {}, true],
  ["[referrer] !== [referrer]", {}, false],
  ["[[undefined]] == [[undefined]]", {}, true],
  ["[[undefined]] != [[undefined]]", {}, false],
  ["[[undefined]] === [[undefined]]", {}, true],
  ["[[undefined]] !== [[undefined]]", {}, false],
  ["[1, referrer] == [1, referrer]", {}, true],
  ["[1, referrer] != [1, referrer]", {}, false],
  ["[1, referrer] === [1, referrer]", {}, true],
  ["[1, referrer] !== [1, referrer]", {}, false],
  ["[{line2: referrer}] == [{line2: referrer}]", {}, true],
  ["[{line2: referrer}] != [{line2: referrer}]", {}, false],
  ["[{line2: referrer}] === [{line2: referrer}]", {}, true],
  ["[{line2: referrer}] !== [{line2: referrer}]", {}, false],
  ["{line2: undefined} == {}", {}, false],
  ["{line2: undefined} != {}", {}, true],
  ["{line2: undefined} === {}", {}, false],
  ["{line2: undefined} !== {}", {}, true],
  ["{line2: undefined} == {line2: null}", {}, false],
  ["{line2: undefined} != {line2: null}", {}, true],
  ["{line2: undefined} === {line2: null}", {}, false],
  ["{line2: undefined} !== {line2: null}", {}, true],
  ["[undefined] == [null]", {}, false],
  ["[undefined] != [null]", {}, true],
  ["[undefined] === [null]", {}, false],
  ["[undefined] !== [null]", {}, true],
  ["billing == {line2: undefined}", { billing: {} }, false],
  ["billing == {line2: null}", { billing: { line2: null } }, true],
  ["{line2: undefined} in [{line2: undefined}]", {}, true],
  ["[{line2: undefined}] contains {line2: undefined}", {}, true],
  ["[undefined] in [[undefined]]", {}, true],
  ["#2026-03-01# == #2026-03-01T00:00:00Z#", {}, true],
  ["#2026-03-01# === #2026-03-01T00:00:00Z#", {}, false],
  ["#2026-03-01T00:00:00Z# == #2026-03-01T00:00:00.000Z#", {}, true],
  ["#2026-03-01T00:00:00.000Z# == #2026-03-01T00:00:00.000000Z#", {}, true],
  ["3d == 3d", {}, true],
  ["3d === 3d", {}, true],
  ["1d == 24h", {}, false],
  ["1d === 24h", {}, false],
  ["3d8h == 3d8h", {}, true],
  ["{opened_on: #2026-03-01#} === {opened_on: #2026-03-01T00:00:00Z#}", {}, false],
  ["[#2026-03-01#] === [#2026-03-01T00:00:00Z#]", {}, false],
  ["{holds: [#2026-03-01#]} === {holds: [#2026-03-01T00:00:00Z#]}", {}, false],
  ["#2026-03-01# in [#2026-03-01T00:00:00Z#]", {}, true],
  ["#2026-03-01T00:00:00Z# in [#2026-03-01T00:00:00.000Z#]", {}, true],
  ["#2026-03-01T00:00:00.000Z# in [#2026-03-01T00:00:00.000000Z#]", {}, true],
  ["{opened_on: #2026-03-01#} == {opened_on: #2026-03-01#}", {}, true],
  ["[#2026-03-01#] == [#2026-03-01#]", {}, true],
  ["{holds: [#2026-03-01#]} == {holds: [#2026-03-01#]}", {}, true],
  ["{opened_on: #2026-03-01#} === {opened_on: #2026-03-01#}", {}, true],
  ["[#2026-03-01#] === [#2026-03-01#]", {}, true],
  ["{holds: [#2026-03-01#]} === {holds: [#2026-03-01#]}", {}, true],
  ["#2026-03-01# in [#2026-03-01#]", {}, true],
  ["{opened_on: #2026-03-01#} in [{opened_on: #2026-03-01#}]", {}, true],
  ["{opened_on: #2026-03-01T00:00:00Z#} == {opened_on: #2026-03-01T00:00:00Z#}", {}, true],
  ["[#2026-03-01T00:00:00Z#] == [#2026-03-01T00:00:00Z#]", {}, true],
  ["{holds: [#2026-03-01T00:00:00Z#]} == {holds: [#2026-03-01T00:00:00Z#]}", {}, true],
  ["{opened_on: #2026-03-01T00:00:00Z#} === {opened_on: #2026-03-01T00:00:00Z#}", {}, true],
  ["[#2026-03-01T00:00:00Z#] === [#2026-03-01T00:00:00Z#]", {}, true],
  ["{holds: [#2026-03-01T00:00:00Z#]} === {holds: [#2026-03-01T00:00:00Z#]}", {}, true],
  ["#2026-03-01T00:00:00Z# in [#2026-03-01T00:00:00Z#]", {}, true],
  ["{opened_on: #2026-03-01T00:00:00Z#} in [{opened_on: #2026-03-01T00:00:00Z#}]", {}, true],
  ["{opened_on: 3d} == {opened_on: 3d}", {}, true],
  ["[3d] == [3d]", {}, true],
  ["{holds: [3d]} == {holds: [3d]}", {}, true],
  ["{opened_on: 3d} === {opened_on: 3d}", {}, true],
  ["[3d] === [3d]", {}, true],
  ["{holds: [3d]} === {holds: [3d]}", {}, true],
  ["3d in [3d]", {}, true],
  ["{opened_on: 3d} in [{opened_on: 3d}]", {}, true],
  ["{opened_on: 1d} == {opened_on: 24h}", {}, false],
  ["[1d] == [24h]", {}, false],
  ["{holds: [1d]} == {holds: [24h]}", {}, false],
  ["{opened_on: 1d} === {opened_on: 24h}", {}, false],
  ["[1d] === [24h]", {}, false],
  ["{holds: [1d]} === {holds: [24h]}", {}, false],
  ["1d in [24h]", {}, false],
  ["{opened_on: 1d} in [{opened_on: 24h}]", {}, false],
  ["{opened_on: 3d8h} == {opened_on: 3d8h}", {}, true],
  ["[3d8h] == [3d8h]", {}, true],
  ["{holds: [3d8h]} == {holds: [3d8h]}", {}, true],
  ["{opened_on: 3d8h} === {opened_on: 3d8h}", {}, true],
  ["[3d8h] === [3d8h]", {}, true],
  ["{holds: [3d8h]} === {holds: [3d8h]}", {}, true],
  ["3d8h in [3d8h]", {}, true],
  ["{opened_on: 3d8h} in [{opened_on: 3d8h}]", {}, true],
  ["undefined == undefined", {}, undefined],
  ["undefined != undefined", {}, undefined],
  ["undefined === undefined", {}, true],
  ["undefined !== undefined", {}, false],
  ["undefined in [undefined]", {}, undefined],
  ["undefined in [1]", {}, undefined],
  ["1 in [undefined]", {}, false],
  ["undefined in undefined", {}, undefined],
  ["1 in undefined", {}, undefined],
  ["[undefined] contains undefined", {}, undefined],
  ["referrer === referrer", {}, true],
  ["holds in [holds]", { holds: null }, true],
];

describe("member equality inside lists and maps", () => {
  it.each(ROWS)("%s against %j answers %s, as the reference does", (source, context, answer) => {
    expect(evaluate(source, context)).toEqual({ ok: true, value: answer });
  });
});
